import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { CustomeNextPage } from "../types/CustomNextPage";

const Home: CustomeNextPage = () => {
  const { data, status } = useSession();

  return (
    <>
      <Head>
        <title>INVENTORY APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.user?.name || <Link href={"/auth/signin"}>GOTO SIGN</Link>}
        {status === "authenticated" && (
          <button onClick={() => signOut()}> SIGN OUT</button>
        )}
      </main>
      <Link href={"/categories"} legacyBehavior>
        <a style={{ marginLeft: "1rem" }}>PROTECTED PAGE</a>
      </Link>
    </>
  );
};

Home.requireAuth = true;

export default Home;
